import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  const navigation: { name: string; path: string }[] = [
    {
      name: 'Home',
      path: '/',
    },
    {
      name: 'Dashboard',
      path: '/dashboard',
    },
  ]

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex w-full items-center justify-start gap-5">
          {navigation.map((el) => (
            <Link href={el.path} key={el.name}>
              {el.name}
            </Link>
          ))}
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}

export default RootLayout
